@startuml
title Relation Schema
hide circle
entity "USER" as User {
  (PK)user_id
  --
  user_photo
  nickname
  email
}

entity "AIR CLEANNESS" as airCleanness {
  (PK)user_id
  --
  Dust_amount
  (FK) user_id
}

entity "SELF-ESTEEM DEVELOPMENT COMPLEX" as SelfEstDevComplx {
  (PK) SelfEstComplex_id
  --
  t1tle
  Content
  Link
  (FK)user_id
}

User --{ airCleanness
User --{ SelfEstDevComplx

@enduml
