@startuml
title UseСaseDiagram
actor "Cпоживач" as actor

rectangle System {
    usecase (Проробити комплекс nрозвитку самоповаги) as usecase1 
    usecase (Знайти комплекс розвитку самоповаги) as usecase2

    actor -- usecase1
    usecase1 .> usecase2 : include
}
@enduml
