@startuml
title Conditional - Activity Diagram 

start
:Користувач вводить назву населеного пункту;
:Програма шукає усі населені пункти з назвою, яку користувач ввів;
if (Результати пошуку знайдено?) then (Yes)
  :Отримано інформацію про чистоту повітря!;
else (No)
  :Упс, помилка, такого населеного пункту нема, спробуйте ще раз!;
endif
stop

@enduml
