@startuml
title UseСaseDiagram
actor "Cпоживач" as act #Green

rectangle System {
    usecase (Проробити комплекс nрозвитку самоповаги) as use1 #LightBlue
    usecase (Знайти комплекс розвитку самоповаги) as use2 #Pink

    act -- use1
    use1 .> use2 : include
}
@enduml
